import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Team from '../components/Team'
import Footer from '../components/Footer'
import { Divider } from '@chakra-ui/react'
import Head from 'next/head'
import type { NextPage } from 'next'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })



const Home: NextPage = () => {

    // hook which help us to toggle the color modes

    return (
        <>
            <Head>
                <title>Noble Fable - About</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="https://cdn.discordapp.com/attachments/923864185799082005/1106513392010792961/Logo_2.png" />
            </Head>
            <Navbar />
            <About />
            <Divider />
            <Team />
            <Footer />
        </>
    )
}

export default Home

