import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import CardProject from '../components/CardProject'
import ProjectCount from '../components/ProjectCount'
import Hero from '../components/Hero'
import Footer from '../components/Footer'
import Head from 'next/head'
import type { NextPage } from 'next'
import styles from '../styles/Home.module.css'
import { useColorMode } from '@chakra-ui/color-mode'
import React from 'react'
import { Heading } from '@chakra-ui/layout'
import {
  MoonIcon,
  SunIcon
} from '@chakra-ui/icons';
import { IconButton } from '@chakra-ui/button'
import { Divider } from '@chakra-ui/react'
import { Switch } from '@chakra-ui/react'
import { useState, useEffect } from 'react';


const inter = Inter({ subsets: ['latin'] })



const Home: NextPage = () => {

  // hook which help us to toggle the color modes
  const { colorMode, toggleColorMode } = useColorMode()

  return (
    <>
      <Head>
        <title>YaJok Group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://cdn.discordapp.com/attachments/1063724608894812191/1072117727642267738/sticker_9.png" />
      </Head>
      <Navbar />
      <Hero />
      <ProjectCount />
      <CardProject />

      <Footer />
    </>
  )
}

export default Home

